#ifndef __SCP_HEAD_MSG_TYPE_H_
#define __SCP_HEAD_MSG_TYPE_H_

enum SCP_RET_VALUE{
	SCP_RET_FAILED,
	SCP_RET_SUCCESS,
	SCP_RET_WRONG
};


enum SCP_HEAD_MSG_TYPE{
	SCP_HEAD_MSG_CONNECT_REQUEST = 0, //客户端链接申请
	SCP_HEAD_MSG_CONNECT_SUCCESS , //服务器链接成功应答
	SCP_HEAD_MSG_CONNECT_FAILED //服务器链接成功应答
};



#endif
